Modal popup
Kwaleyela-Ikafa/Portfolio-project pull request #10
Opened 2022-07-20 14:19 UTC by Kwaleyela-Ikafa

in this branch we:
- Added a popup modal 
- Modal appears when the see my project button of the Multi-Post Stories card is clicked

2022-07-20 17:19 UTC, sumairq requested changes
## Hi Team, 

<img src="https://media3.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif"/>
Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Interactive elements are working correctly
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR

## Required Changes ♻️

- [x] In the "Works" section the cards after the first card should have a different layout that should not display the `See Project `  button. Kindly fix this issue. Cheers 👍 

Figma Design             |  Your Design
:-------------------------:|:-------------------------:
 ![image](https://user-images.githubusercontent.com/60618877/180042675-904ef5bf-eb66-4a49-b9c8-450bb369226c.png) | ![image](https://user-images.githubusercontent.com/60618877/180042931-82d775b8-0b5b-4429-9d29-67e4f6d0723d.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-20 22:08 UTC, vechicin requested changes
# Hi @Kwaleyela-Ikafa ✋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🚨 


 ## Highlights ⚡ 

- [x] Good job implementing some of the previous reviewer's requirements.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 📂 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-20 22:08 UTC, vechicin commented on styles.css
> +}
On the mobile version, I can only see the modal window when I click on the first project, none of the other cards display a modal window. Please fix that.

Additionally, the modal window is not properly displayed on the page.

<img width="226" alt="Screen Shot 2022-07-20 at 17 00 48" src="https://user-images.githubusercontent.com/82426682/180090045-ced136d4-d42b-454b-8145-8a3785481782.png">

<img width="187" alt="Screen Shot 2022-07-20 at 17 01 09" src="https://user-images.githubusercontent.com/82426682/180090090-aec3ff01-0b0c-4f9a-9956-50d3e9b901c9.png">

You need to make sure the background is blurred just like in the Figma design and that, as long as the modal window is open, the user can only see the modal window's content even if they scroll up and down the page.

2022-07-20 22:08 UTC, vechicin commented on styles.css
> +}
While you did address the previous reviewer's requirement, you didn't do so properly.

<img width="1440" alt="Screen Shot 2022-07-20 at 17 04 54" src="https://user-images.githubusercontent.com/82426682/180090581-229ca77c-038b-4e34-bcc8-ad4d6c00b132.png">

<img width="812" alt="Screen Shot 2022-07-20 at 17 05 59" src="https://user-images.githubusercontent.com/82426682/180090690-977c6d0c-ca42-4c24-8629-db938b6e611a.png">

Please make sure your modal window positioning matches that of the Figma design. Make sure you fix the list of technologies' font as well.

2022-07-22 05:52 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @Kwaleyela-Ikafa        , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

[OPTIONAL] Kindly add a screenshot to your README file showing your webpage user Interface. You can use extentions like fireshot to capturer the entire page.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 05:55 UTC, merged